spring.application.name=RoleBasedAuthentication



# without db (user n pass provided by spring) delete it later
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration



#  Database
# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/rolebasedauth

# MySQL username & password
spring.datasource.username=root
spring.datasource.password=root

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA settings

# ddl =update update it in db
# see queries in log

spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# formatsql = give queries in readable format
# add this
spring.jpa.properties.hibernate.format_sql=trueLDialect